### PR TITLE
Audit_Album_details

### PR DESCRIPTION
**Pull request by coryj1990**

### CODE REVIEW

**Comment by coryj1990** [comment]
I haven't been able to find a way to display images on an album details page. A lot of my searches include solutions for image_tag (instance variable).image_url.to_s injected to the view page, but I keep getting an error about how there is no method defined as .image_url. The albums show view is what I am looking at.
1. go to albums 
2. click on Details (If you cloned my code click on the second one. My db only has files for the second album.
3. Page should show details with images saved in db for album
4. Error appears as undefined method `image_url' for #Photo::ActiveRecord_Relation:0x007fd0e7e76980

I have tried other variations of (__)_url to fit how my variables are named in my code, but nothing seems to be working.

**Comment by coryj1990** [comment]
Something worth noting: There needs to be some other software like RMagick or MiniMagick if we are to use carrierwave to store and resize images into thumbnails. As I am typing this I didn't bother seeing if there was some other way to display an image with height and width constraints, but from my search in using carrierwave to apply those constraints, the results wanted to download/install those two software things.

**Comment by halfghaninne** [comment]
- [x] `Release date` is not formatted like it is in the design comp
- [ ] Where is `Label`?
- [x] Where are album tracks?
- [ ] When I created an Album, I was not asked to add any images,  so there are no images to display on the show page.
- [ ] There is a link to Upload Album images on the Album show page that [does not exist in the design comp](https://projects.invisionapp.com/share/AY6N3DEB5#/screens/145633696)

**Comment by coryj1990** [comment]
From the discussion here https://github.com/omahacodeschool/vinyl-archive/issues/39 it was determined that the focus of the audit were just on the album details page. Adding label information belongs in the creation of the album. Making the ability to add images for an album was a goal; the location of those abilities wasn't specified. 

Tracks for the albums, formatting release dates are what I will work on until further notice.

**Comment by sumeetjain** [comment]
@coryj1990 Make a new issue for the pieces Alex cited: the label and album images. That way someone else can work on those features.

The other thing she mentioned seems valid to me:

> There is a link to Upload Album images on the Album show page that does not exist in the design comp

Is something is on the page that shouldn't be, delete it.

**Comment by coryj1990** [comment]
https://github.com/omahacodeschool/vinyl-archive/issues/52

**Pull request merged**
