### PR TITLE
Format filter

### PR DESCRIPTION
**Pull request by cnarans**

### CODE REVIEW

**Comment by halfghaninne** [comment]
What happens if there are no albums for a given format?

**Comment by cnarans** [comment]
The function returns an empty array and no albums are displayed.  Should I test for that?

**Comment by halfghaninne** [comment]
I see that your tests pass if no Albums are in the database. 

When I actually walk through the application locally, I get this error when I try to sort by `Single` (none of the Albums I have locally are Singles):

screen shot 2016-08-18 at 2 50 09 pm

Does the same happen for you?

**Comment by cnarans** [comment]
No, mine doesn't do that.  filter should return an empty array if there are no matches, so it shouldn't be giving a nil error.  I'm not sure what's going on with the error.

upload

**Comment by halfghaninne** [comment]
Hm. Nice. I deleted my Albums locally and see the problem is no longer persisting!  ¯_(ツ)_/¯

**Comment by halfghaninne** [comment]
If this is ready to review, head up and we can check out this merge conflict!

**Pull request merged**
